# fly.toml app configuration file generated for grad-connect-api on 2026-05-02T17:07:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grad-connect-api'
primary_region = 'fra'

[build]
dockerfile = "Dockerfile"
[build.args]
GO_VERSION = '1.25.0'

# [deploy]
# release_command = "/app/migrate -path=/app/migrations -database=$GRADCONNECT_DB_DSN -lock-timeout=60 up"

[env]
GRADCONNECT_PORT = "8080"
GRADCONNECT_ENV = "production"
GRADCONNECT_CORS_TRUSTED_ORIGINS = "https://gradconnect.ng https://www.gradconnect.ng"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/v1/healthcheck"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[processes]
app = "/app/api"
